let animals = [
       {
         id: 1,
         name: "Luna",
         imgSrc: "./assets/images/luna.jpg",
         type: "Cat",
         age: "4 years",
         character: ["Curious", "Affectionate", "Fast"],
         favToy: "Mouse",
         owner: "Gabriela",
         ownerUrl: "https://github.com/gabrysia694",
       },
       {
         id: 2,
         name: "Pusho",
         imgSrc: "./assets/images/pusho.jpeg",
         type: "Cat",
         age: "4 years",
         character: ["Fighter", "Playful", "Friendly"],
         favToy: "Laser Light",
         owner: "Farhan",
         ownerUrl: "https://github.com/Gallantfarhan",
       },
       {
         id: 3,
         name: "Gruba",
         imgSrc: "./assets/images/gruba.PNG",
         type: "Cat",
         age: "3 years",
         character: ["Lazy", "Sleepy", "Vocal"],
         favToy: "Laser Light",
         owner: "Gabriela",
         ownerUrl: "https://github.com/gabrysia694",
       },
       {
         id: 4,
         name: "August",
         imgSrc: "./assets/images/August.jpg",
         type: "Cat",
         age: "2 years",
         character: ["Playful", "Adaptable", "Quirky"],
         favToy: "Foil Ball",
         owner: "Ivan",
         ownerUrl: "https://github.com/marehori",
       },
       {
         id: 5,
         name: "Cooper",
         imgSrc: "./assets/images/Cooper.jpg",
         type: "Dog",
         age: "5 years",
         character: ["Loyal", "Protective", "Friendly"],
         favToy: "Chew Rope",
         owner: "Sujal",
         ownerUrl: "https://github.com/Sranjan0208",
       },
       {
         id: 6,
         name: "Bubble",
         imgSrc: "./assets/images/Goldfish.jpg",
         type: "Goldfish",
         age: "2 years",
         character: ["Social", "Playful", "Adaptable"],
         favToy: "Ping Pong Balls",
         owner: "Vishal",
         ownerUrl: "https://github.com/Vishal-Parasram",
       },
       {
         id: 7,
         name: "Little Mike",
         imgSrc: "./assets/images/littlemike.jpg",
         type: "Cat",
         age: "1 years",
         character: ["Crazy", "Playful", "Active"],
         favToy: "Me",
         owner: "Valerio",
         ownerUrl: "https://github.com/ValerioPinsone",
       },
       {
         id: 8,
         name: "Whiskey",
         imgSrc: "./assets/images/whiskeys1.jpg",
         type: "Dog",
         age: "2 years",
         character: ["Energetic", "Enthusiastic", "Adaptable"],
         favToy: "Ping Pong Balls",
         owner: "Tanuj",
         ownerUrl: "https://github.com/Yuva0",
       },
       {
         id: 9,
         name: "Shadow",
         imgSrc: "./assets/images/shadowCandid.jpg",
         type: "Cat",
         age: "1 and half year",
         character: ["Energetic", "Curious", "Playful"],
         favToy: "Feather wand",
         owner: "Haris",
         ownerUrl: "https://github.com/harisdev-netizen",
       },
       {
         id: 10,
         name: "Amber",
         imgSrc: "./assets/images/hamster.jpg",
         type: "Hamster",
         age: "2 years",
         character: ["Joyful", "Playful", "Freaky"],
         favToy: "Willow Balls",
         owner: "Sandeep",
         ownerUrl: "https://github.com/SANDEEP-NAYAK",
       },
       {
        id: 11,
        name: "Max",
        imgSrc: "./assets/images/max.jpg",
        type: "Dog",
        age: "3 years",
        character: ["Friendly", "Hella Smart", "Energetic"],
        favToy: "Chew Rope",
        owner: "Ankit",
        ownerUrl: "https://github.com/AnandMastery17",
      },
       {
        id: 12,
        name: "Oreo",
        imgSrc: "./assets/images/oreo.jpg",
        type: "Cat",
        age: "7 years",
        character: ["Curious", "Lazy", "Sleepy"],
        favToy: "Legs",
        owner: "Akhil",
        ownerUrl: "https://github.com/Zaris47",
      },
       {
        id: 13,
        name: "Borf",
        imgSrc: "./assets/images/borf.jpg",
        type: "Dog",
        age: "10 years",
        character: ["Lazy", "Friendly", "Fatty"],
        favToy: "Squeaky Gloves",
        owner: "Ian",
        ownerUrl: "https://github.com/IanLuong",
      },
       {
        id: 14,
        name: "Pippa",
        imgSrc: "./assets/images/pippa.jpg",
        type: "Dog",
        age: "5 years",
        character: ["Sleepy", "Hungry", "Barky"],
        favToy: "Ball",
        owner: "Kaleb",
        ownerUrl: "https://github.com/KalebArmbrust",
      },
       {
        id: 15,
        name: "Grim",
        imgSrc: "./assets/images/grim.jpg",
        type: "og",
        age: "4 years",
        character: ["Friendly", "Energetic", "Intelligent"],
        favToy: "Frisbee",
        owner: "Akshat",
        ownerUrl: "https://github.com/KyloRen04",
      },
       {
        id: 16,
        name: "Eren",
        imgSrc: "./assets/images/eren.jpg",
        type: "Dog",
        age: "6 years",
        character: ["Clingy", "Brave", "Mean"],
        favToy: "Socks",
        owner: "Gabriela",
        ownerUrl: "https://github.com/gabrysia694",
      },
       {
        id: 17,
        name: "Maxwell",
        imgSrc: "./assets/images/maxwell.jpeg",
        type: "Cat",
        age: "one years",
        character: ["Playful", "Sneaky", "Lovely"],
        favToy: " Stuffed animal",
        owner: "Isuru",
        ownerUrl: "https://github.com/isurumaldeniya",
      },
       {
        id: 18,
        name: "Max",
        imgSrc: "./assets/images/Max-2.jpg",
        type: "Dog",
        age: "12 years",
        character: ["Hungry", "Lazy", "Friendly"],
        favToy: "Stuffed Animals",
        owner: "josh",
        ownerUrl: "https://github.com/josh76543210",
      },
       {
        id: 19,
        name: "Snowey",
        imgSrc: "./assets/images/Snowey.jpg",
        type: "Cat",
        age: "2 years",
        character: ["Energetic", "FearLess", "Playful"],
        favToy: "Wool",
        owner: "Piethon",
        ownerUrl: "https://github.com/Pyth0nHere",
      },
       {
        id: 20,
        name: "Feijão",
        imgSrc: "./assets/images/feijao.jpg",
        type: "Cat",
        age: "10 years",
        character: ["Talkative", "Lazy", "Clingy"],
        favToy: "Strings",
        owner: "Pedro",
        ownerUrl: "https://github.com/paternostrox",
      },
       {
        id: 21,
        name: "Lilly",
        imgSrc: "./assets/images/lilly.jpg",
        type: "Cat",
        age: "2 years",
        character: ["Sleepy", "Funny", "Curious"],
        favToy: "Teddy",
        owner: "Soundarya Koutharapu",
        ownerUrl: "https://github.com/SoundaryaKoutharapu",
      },
       {
        id: 22,
        name: "Peeru",
        imgSrc: "./assets/images/peeru.jpg",
        type: "Dog",
        age: "1 years",
        character: ["Cuteness", "Funny", " "],
        favToy: "Ball",
        owner: "Pedro",
        ownerUrl: "https://github.com/roy2pushkar",
      },
       {
        id: 23,
        name: "Shiro",
        imgSrc: "./assets/images/shiro.jpg",
        type: "Dog",
        age: "5 years",
        character: ["Sleepy", "Clingy","Curious"],
        favToy: "Ball",
        owner: "Souvik",
        ownerUrl: "https://github.com/Souvik2376",
      },


      
     ]

